---
title: "networks_only"
author: "Annabelle"
date: "June 5, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
adjmatrix <- read_csv("/usr/local/bin/store/partner_rff/output/adjacencymatrix.csv") #this isn't set up correctly 
#need to convert first column to rownames
rownames(adjmatrix) <- adjmatrix$X1 #set partnernames as rownames
adjmatrix[,1] <- NULL #then remove column 

as.numeric(adjmatrix)
class(adjmatrix)

library(tidyverse)
library(igraph)
library(netrankr) #package for network centrality
```

```{r}
p <- graph_from_adjacency_matrix(adjmatrix, mode = c("directed"))
?graph_from_adjacency_matrix
```




```{r}
rawdf <- condense
#remove extra columns 
rawdf <- rawdf[,-c(1,2)]
trn <- t(rawdf)
again <- t(trn)
is.numeric(trn)
is.numeric(again)

trial1 <- trn %*%  again

#double check numbers 
colSums(rawdf) #checks out!! 


```

```{r}
ac <- graph_from_adjacency_matrix(trial1, mode = c("directed"))
print(ac)
```


change trial1 to edge list 

```{r}
mymat1 <- trial1
diag(mymat1) <- 0

colnames(mymat1)

library(igraph)

wegoagain <- graph.adjacency(
  adjmatrix = mymat1, 
  mode = "undirected", 
  weighted = TRUE)

plot.igraph(wegoagain)

# Set node size based on audience size:
V(wegoagain)$size <- V(wegoagain)$audience.size*0.7


```


new scrap work 
```{r}
#set igraph object from adj matrix 

yikes <- graph_from_adjacency_matrix(trial1, mode = "undirected")
plot(yikes)

```

```{r}
ac <- graph_from_adjacency_matrix(trial1, mode = c("directed"))
E(ac)       # The edges of the "net" object

V(ac)       # The vertices of the "net" object

E(ac)$type  # Edge attribute "type"


as_edgelist(ac, names=T) #issue is that printing for every value defined in cell 

```


having a bunch of package issues 
```{r}
install.packages(ggnet2)
library(ggnet2)

install.packages("installr")
library(installr)
updateR()

```





```{r}
install.packages("flowers") #not able to install - "not available for R verison 3.5.2"
library(flowers)
data(ohi)
plot_flower(ohi, "OHI Example")
```

try to reformat threats adjmat bc smaller

--> everything not commented out works 
but circle size doesn't correspond to correct label 

source of issue? - "number of items to replace is not a multiple of replacement length"
```{r}
tadjmat <- threatmat

tadjmat[lower.tri(tadjmat)] <- NA
diag(tadjmat) <- NA

tolist <- tadjmat %>% melt() 
tolist <- tolist[-which(is.na(tolist$value)),]

#nsize <- tolist %>% filter((Var1 == Var2)) #set new vector with diag values
#tolist <- tolist %>% filter((Var1 != Var2)) 

#allthreat <- tolist %>% right_join(nsize, by = c("Var1"))
#allthreat <- allthreat[,-c(4)]

library(igraph)

net <- graph_from_data_frame(d=tolist, directed=T) 


#plot(net, edge.arrow.size=.2, edge.curved=0,

  #   vertex.color="orange", vertex.frame.color="#555555",

   #  vertex.label=V(net)$Var1, vertex.label.color="black",

   #  vertex.label.cex=.7, vertex.size = net$value.y)

E(net)$arrow.size <- .2 #determine size of arrows (this makes the heads real small so they are more like lines)
#V(net)$names <- c("a","b","c","d","e","f","g","h") #naming the nodes -- try this later so don't over write what actal names are 
#V(df)$names <- c("hab_x_x", "over_x_x", "poll_x_x", "spsp_x_x", "env_x_x", "demo_x_x")
node.size<-setNames(c(30,5,3,17,8,11), c("hab_x_x", "over_x_x", "poll_x_x", "spsp_x_x", "env_x_x", "demo_x_x"))
  #so not setting in the same order 
V(net)$label <- NA
E(net)$width <- E(net)$value

plot(net, vertex.size=node.size)


#plot(net, edge.arrow.size=0.01,vertex.label.color = "black", vertex.size=node.size)

```


Ex on stackoverflow used to figure out node size 
```{r}
set.seed(1410)
df<-data.frame(
"site.x"=c(rep("a",4),rep("b",4),rep("c",4),rep("d",4)),
"site.y"=c(rep(c("e","f","g","h"),4)),
"bond.strength"=sample(1:100,16, replace=TRUE))
View(df)

df<-graph.data.frame(df)
V(df)$names <- c("a","b","c","d","e","f","g","h")
layOUT<-data.frame(x=c(rep(1,4),rep(2,4)),y=c(4:1,4:1))
E(df)[ bond.strength < 101 ]$color <- "red"
E(df)[ bond.strength < 67 ]$color <- "yellow"
E(df)[ bond.strength < 34 ]$color <- "green"
V(df)$color <- "white"

l<-as.matrix(layOUT)
plot(df,layout=l,vertex.size=10,vertex.label=V(df)$names,
edge.arrow.size=0.01,vertex.label.color = "black")



node.size<-setNames(c(25, 15, 35, 5, 10, 5, 19, 44),c("a", "b","c", "d", "e", "f", "g", "h"))
plot(df,layout=l,vertex.label=V(df)$names,
edge.arrow.size=0.01,vertex.label.color = "black",vertex.size=node.size)

```



```{r}
tactadjmat <- trial1

tactadjmat[lower.tri(tactadjmat)] <- NA
diag(tactadjmat) <- NA

actlist <- tactadjmat %>% melt() 
actlist <- actlist[-which(is.na(actlist$value)),]

#nsize <- tolist %>% filter((Var1 == Var2)) #set new vector with diag values
#tolist <- tolist %>% filter((Var1 != Var2)) 

#allthreat <- tolist %>% right_join(nsize, by = c("Var1"))
#allthreat <- allthreat[,-c(4)]

library(igraph)

actnet <- graph_from_data_frame(d=actlist, directed=T) 


#plot(net, edge.arrow.size=.2, edge.curved=0,

  #   vertex.color="orange", vertex.frame.color="#555555",

   #  vertex.label=V(net)$Var1, vertex.label.color="black",

   #  vertex.label.cex=.7, vertex.size = net$value.y)

E(actnet)$arrow.size <- .2 #determine size of arrows (this makes the heads real small so they are more like lines)
#V(net)$names <- c("a","b","c","d","e","f","g","h") #naming the nodes -- try this later so don't over write what actal names are 
#V(df)$names <- c("hab_x_x", "over_x_x", "poll_x_x", "spsp_x_x", "env_x_x", "demo_x_x")
node.size<-setNames(c(66,35,10,2,4,48,34,54,19,62,33), c("X1..Land.Water.Management" ,"X2..Species.Management", "X3..Awareness.raising", "X4..law.enforcement.and.prosecution" , "X5..livelihood..economic.and.moral.incentrives", "X6..Conservation.Design.and.Planning","X7..Legal.and.Policy.frameworks","X8..Research.and.monitoring" ,"X9..Education.and.Training","X10..Institutional.Development","funding"))
 

#so not setting in the same order 


E(actnet)$width <- E(actnet)$value*.35 

plot(actnet, vertex.size=node.size*.5)


#plot(net, edge.arrow.size=0.01,vertex.label.color = "black", vertex.size=node.size)


node.size<-setNames(c(66,35,10,2,4,48,34,54,19,62,33), c("LandWaterMan" ,"SpeciesMan", "AwarRaise", "law.enforce" , "livelihood_economic_moral", "Conservation.D&P","Legal.and.Policy","Research.and.monitoring" ,"Edu_Training","Institutional.Dev","funding")) #tried resetting names but nothing happened 
 

l <- layout_with_fr(actnet)
plot(actnet, layout = l, vertex.size=node.size*.5)


l <- layout_on_grid(actnet)
plot(actnet, vertex.label=NA, layout = l, vertex.size=node.size*.75)


```




Want to try a three-d thing 

```{r}
library(scatterplot3d)
#remove eastern cottentail 
nobunny <- regdf
nobunny <- nobunny[-c(35),]
x <- nobunny$total_x_x #total number of threats for each species
y <- nobunny$actionsum
z <- nobunny$total

G  <- scatterplot3d(z, y, x, highlight.3d = FALSE, type = "h", grid=TRUE, ylim = c(10,0), zlab="threats count", ylab="actions count", xlab="partners count")

```

